### ISSUE TITLE
Make server compatible with AWS DocumentDB

### ISSUE THREAD

**Issue by nielstenboom** [allegroai/clearml-server#101]
Hi there! I have deployed an AWS DocumentDB for the apiserver because I'd rather not manage the database myself. But unfortunately ran into the issue that documentdb is not compatible with the Clearml apiserver because it's using `text` index types:

```
[2022-01-05 15:31:15,382] [10] [ERROR] [clearml.service_repo] Index type not supported : text
Traceback (most recent call last):
  File "/opt/clearml/apiserver/service_repo/service_repo.py", line 277, in handle_call
    ret = endpoint.func(call, company, call.data_model)
  File "/opt/clearml/apiserver/services/projects.py", line 115, in get_all_ex
    company=company_id, query_dict=data, allow_public=allow_public,
  File "/opt/clearml/apiserver/database/model/base.py", line 532, in get_many_with_join
    allow_public=allow_public,
  File "/opt/clearml/apiserver/database/model/base.py", line 612, in get_many
    override_collation=override_collation,
  File "/opt/clearml/apiserver/database/model/base.py", line 754, in _get_many_override_none_ordering
    query_sets = [cls.objects(query)]
  File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/usr/local/lib/python3.6/site-packages/mongoengine/document.py", line 220, in _get_collection
    cls.ensure_indexes()
  File "/usr/local/lib/python3.6/site-packages/mongoengine/document.py", line 924, in ensure_indexes
    collection.create_index(fields, background=background, **opts)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 1995, in create_index
    self.__create_index(keys, kwargs, session, **cmd_options)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 1894, in __create_index
    session=session)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 250, in _command
    user_fields=user_fields)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/pool.py", line 613, in command
    user_fields=user_fields)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/network.py", line 167, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Index type not supported : text
```

I'm not sure if this is an easy fix, I can imagine if this is a breaking change you'd rather not do it. But if it's not it would be great ClearML would be compatible with AWS DocumentDB!

**Comment by jkhenning** [comment]
Hi @nielstenboom ,

The text indices are used to provide free text search - without them, we'll be losing a feature  🙁

**Comment by nielstenboom** [comment]
Ahh yeah makes sense, I was already afraid of that. I'll look into setting up a MongoDB in a different way. I'll close the issue right away as it's not feasible!
