### ISSUE TITLE
`events.get_scalar_metrics_and_variants` returns 500 error from ClearML SaaS server

### ISSUE THREAD

**Issue by bdalal** [allegroai/clearml-server#120]
Hi,
I'm trying to run the following API call
```
# Imports
...
client = APIClient()
resp = client.events.get_scalar_metrics_and_variants("MY_TASK_ID")
```
but it errors out with
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/binoydalal/miniconda3/envs/DS974/lib/python3.9/site-packages/clearml/backend_api/session/client/client.py", line 376, in new_func
    return Response(self.session.send(request_cls(*args, **kwargs)))
  File "/home/binoydalal/miniconda3/envs/DS974/lib/python3.9/site-packages/clearml/backend_api/session/client/client.py", line 122, in send
    raise APIError(result)
clearml.backend_api.session.client.client.APIError: APIError: code 500: 'str' object has no attribute 'value'
```
Based on the schema definition [here](https://github.com/allegroai/clearml-server/blob/04ea9018a3c0cbb8a9e0044e5a24110883a0abfa/apiserver/schema/services/events.conf#L1170), I think I'm making the call correctly.

CML Client version 1.1.6
I'm on the CML hosted SaaS server

CC @jkhenning

**Comment by jkhenning** [comment]
Closing this as it was already fixed in released versions. Please reopen if required.
