### ISSUE TITLE
Invalid mongodb connection string if CLEARML_MONGODB_SERVICE_CONNECTION_STRING is specified

### ISSUE THREAD

**Issue by smartnet-club** [allegroai/clearml-server#252]
`CLEARML_MONGODB_SERVICE_CONNECTION_STRING=mongodb://myDBReader:D1fficultP%40ssw0rd@mongodb0.example.com:27017/?authSource=admin`

**expected** connection string:
`mongodb://myDBReader:D1fficultP%40ssw0rd@mongodb0.example.com:27017/auth?authSource=admin`

**actual** connection string:
`mongodb://myDBReader:D1fficultP%40ssw0rd@mongodb0.example.com:27017/?authSource=admin/auth`

**must be fixed** [database package](https://github.com/allegroai/clearml-server/blob/83a0485518664c2a8f3965d9b103298a9f4e4b79/apiserver/database/__init__.py#L84)
`con_str = f"{override_connection_string.rstrip('/')}/{key}"`

**Comment by ainoam** [comment]
Thanks for letting us know @smartnet-club - We'll take a look.

**Comment by evg-allegro** [comment]
@smartnet-club We reproduced the issue. It will be fixed in the upcoming open source version (v1.17)

**Comment by pollfly** [comment]
Hey @smartnet-club! Just letting you know that this issue has been resolved in the recently released [v1.17.0](https://github.com/allegroai/clearml-server/releases/tag/v1.17.0). Let us know if there are any issues :)

**Comment by smartnet-club** [comment]
Error parsing mongodb replica set connection string.

Connection string: `"mongodb://user:password@host1:27017,host2:27017,host3:27017/database?replicaSet=myReplicaSet"`

Error:
```
apiserver-1  | Traceback (most recent call last):
apiserver-1  |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
apiserver-1  |     return _run_code(code, main_globals, None,
apiserver-1  |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
apiserver-1  |     exec(code, run_globals)
apiserver-1  |   File "/opt/clearml/apiserver/server.py", line 10, in <module>
apiserver-1  |     AppSequence(app).start(request_handlers=RequestHandlers())
apiserver-1  |   File "/opt/clearml/apiserver/server_init/app_sequence.py", line 42, in start
apiserver-1  |     self._init_dbs()
apiserver-1  |   File "/opt/clearml/apiserver/server_init/app_sequence.py", line 72, in _init_dbs
apiserver-1  |     db.initialize()
apiserver-1  |   File "/opt/clearml/apiserver/database/__init__.py", line 84, in initialize
apiserver-1  |     con_str = furl(override_connection_string).add(path=key).url
apiserver-1  |   File "/usr/local/lib/python3.9/site-packages/furl/furl.py", line 1381, in __init__
apiserver-1  |     self.load(url)  # Raises ValueError on invalid URL.
apiserver-1  |   File "/usr/local/lib/python3.9/site-packages/furl/furl.py", line 1408, in load
apiserver-1  |     self.netloc = tokens.netloc  # Raises ValueError in Python 2.7+.
apiserver-1  |   File "/usr/local/lib/python3.9/site-packages/furl/furl.py", line 1889, in __setattr__
apiserver-1  |     object.__setattr__(self, attr, value)
apiserver-1  |   File "/usr/local/lib/python3.9/site-packages/furl/furl.py", line 1535, in netloc
apiserver-1  |     self.host = host
apiserver-1  |   File "/usr/local/lib/python3.9/site-packages/furl/furl.py", line 1889, in __setattr__
apiserver-1  |     object.__setattr__(self, attr, value)
apiserver-1  |   File "/usr/local/lib/python3.9/site-packages/furl/furl.py", line 1450, in host
apiserver-1  |     raise ValueError(errmsg % (host, INVALID_HOST_CHARS))
```

`ValueError: Invalid host 'host1:27017,host2:27017,host3'. Host strings must have at least one non-period character, can't contain any of '!@#$%^&'"*()+=:;/', and can't have adjacent periods.`

**Comment by evg-allegro** [comment]
@smartnet-club Please try with the just released version 1.17.1. The following connection string should work now:
mongodb://user:password@host1:27017,host2:27017,host3:27017?replicaSet=myReplicaSet
Please note that I removed the database in the end because apiserver uses 2 different dbs and adds them when needed
