### ISSUE TITLE
elasticsearch performance issue

### ISSUE THREAD

**Issue by exzhawk** [allegroai/clearml-server#85]
I've set up a ClearML instance using docker-compose in our lab. The whole docker setup runs in a VM with 4 CPU cores and 80GB memory. About 80 experiments are running on other machines, reporting to ClearML. After a while, some experiments are complaining: 
```
2021-09-08 15:25:26,701 - clearml.log - WARNING - failed logging task to backend (1 lines, <500/100: events.add_batch/v1.0 (General data error: err=('1 document(s) failed to index.', [{'index': {'_index': 'events-log-d1bd92a3b039400cbafc60a7a5b1e52b', '_type': '_doc', '_id': '6866c63c61904d15a040c38c37a3d003', 'status': 429, 'error': {'type':..., extra_info=rejected execution of processing of [33460295][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[events-log-d1bd92a3b039400cbafc60a7a5b1e52b][0]] containing [index {[events-log-d1bd92a3b039400cbafc60a7a5b1e52b][_doc][6866c63c61904d15a040c38c37a3d003], source[{"timestamp":1630135522480,"type":"log","task":"c18bdfcb2a574448bb45c155164d86c3","level":"error","worker":"rebound-24D1254A-worker-0","msg":"87it [01:27,  1.23it/s]","@timestamp":"2021-09-08T07:25:26.604Z","metric":"","variant":""}]}] and a refresh, target allocation id: lYBMwDBnThKn0b3e9H6nVA, primary term: 1 on EsThreadPoolExecutor[name = clearml/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@6941a64a[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 21541986]])>)
```
And the ClearML `docker-compose logs` is showing lots of:
```
clearml-apiserver | [2021-09-08 08:45:59,390] [10] [WARNING] [urllib3.connectionpool] Connection pool is full, discarding connection: elasticsearch
```
Does that mean the Elasticsearch service is overloaded? Shall I optimize Elasticsearch configurations or just increase the resources of the ClearML VM? Or maybe a delicate Elasticsearch cluster is a must to handle these experiments?

Any advice is appreciated!

**Comment by jkhenning** [comment]
Hi @exzhawk ,

This looks like an ES optimization issue.

The `Connection pool is full, discarding connection` is not en error, it simply means that connections, once closed, are not kept in a pool (which is full_, but discarded. This can be optimized by raising Python's urllib3 connection pool settings, but is incidental.

Did you update your docker-compose.yml file to add more memory to the `elasticsearch` service?

**Comment by exzhawk** [comment]
> Did you update your docker-compose.yml file to add more memory to the `elasticsearch` service?

After looking up Elasticsearch docs about performance tuning ( https://www.elastic.co/guide/en/elasticsearch/reference/7.14/advanced-configuration.html ), I did raise `Xms` and `Xmx` in `docker-compose.yml` file to 26g.
Now warning in experiments disappeared, but `Connection pool is full` is still there. Will try that later.

**Comment by jkhenning** [comment]
> I did raise Xms and Xmx in docker-compose.yml file to 26g

That sounds like a good choice :)

> Now warning in experiments disappeared, but Connection pool is full is still there. Will try that later.

You can try to configure the Elasticsearch Python client we use to allocate a bigger connection pool (I think the default size is 10 connections). You can do that using the environment ariables `CLEARML__HOSTS__ELASTIC__EVENTS__ARGS__MAXSIZE` and `CLEARML__HOSTS__ELASTIC__WORKERS__ARGS__MAXSIZE` (one for each of the ES "clusters" used by the server) and set their value to a bigger numerical value (note that since this is an env var, the value should be a string)

**Comment by lgerrets** [comment]
Hello @jkhenning ,

I am facing the same issue. Thank you for pointing at these 2 environment variables.

I could not find them in the source code, to see what the default values are. What are the default values when they are not provided? And what values do you recommend?

Many thanks

**Comment by jkhenning** [comment]
Hi @lgerrets ,

These env vars are actually dynamic vars that are parsed by the server's configuration code (see [here](https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_config#dynamic-environment-variables)). These specific vars direct the server to override the default hosts configuration for mongodb (see [here](https://github.com/allegroai/clearml-server/blob/a64c4d264d00eadd2d11818b37151d3cc6266d99/apiserver/config/default/hosts.conf#L25))

**Comment by lgerrets** [comment]
Thank for the links!

Yesterday I rebooted my server and set `CLEARML__HOSTS__ELASTIC__EVENTS__ARGS__MAXSIZE="100"` and `CLEARML__HOSTS__ELASTIC__WORKERS__ARGS__MAXSIZE="4"`. I did not know the default values so I chose these quite randomly.

Since then I haven't noticed the issue anymore. Also the CPU is not saturated anymore.

**Comment by jkhenning** [comment]
Hi @lgerrets ,

> Since then I haven't noticed the issue anymore. Also the CPU is not saturated anymore.

Great to hear 👍 

> I did not know the default values so I chose these quite randomly.I did not know the default values so I chose these quite randomly.

I think the default is 10 for each, but since most of the reporting load is on the events cluster, the `100` setting is the one that probably did the trick 🙂

**Comment by exzhawk** [comment]
seems there is are new issues...
```
clearml-apiserver | [2021-09-17 09:41:00,710] [10] [WARNING] [elasticsearch] POST http://elasticsearch:9200/_bulk?refresh=true [status:N/A request:60.031s]       [44/1805]
clearml-apiserver | Traceback (most recent call last):                                                                                                                     
clearml-apiserver |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request                                                  
clearml-apiserver |     six.raise_from(e, None)                                                                       
clearml-apiserver |   File "<string>", line 3, in raise_from                                                          
clearml-apiserver |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
clearml-apiserver |     httplib_response = conn.getresponse()                                                         
clearml-apiserver |   File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse                           
clearml-apiserver |     response.begin()                                                                              
clearml-apiserver |   File "/usr/lib64/python3.6/http/client.py", line 307, in begin                                  
clearml-apiserver |     version, status, reason = self._read_status()                                                 
clearml-apiserver |   File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status                           
clearml-apiserver |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
clearml-apiserver |   File "/usr/lib64/python3.6/socket.py", line 586, in readinto
clearml-apiserver |     return self._sock.recv_into(b)
clearml-apiserver | socket.timeout: timed out
clearml-apiserver |
clearml-apiserver | During handling of the above exception, another exception occurred:
clearml-apiserver |
clearml-apiserver | Traceback (most recent call last):
clearml-apiserver |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
clearml-apiserver |     method, url, body, retries=Retry(False), headers=request_headers, **kw
clearml-apiserver |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
clearml-apiserver |     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
clearml-apiserver |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 507, in increment
clearml-apiserver |     raise six.reraise(type(error), error, _stacktrace)
clearml-apiserver |   File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
clearml-apiserver |     raise value
clearml-apiserver |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
clearml-apiserver |     chunked=chunked,
clearml-apiserver |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 447, in _make_request
clearml-apiserver |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
clearml-apiserver |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
clearml-apiserver |     self, url, "Read timed out. (read timeout=%s)" % timeout_value
clearml-apiserver | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='elasticsearch', port='9200'): Read timed out. (read timeout=60)
```

![Screenshot_20210917_181509](https://user-images.githubusercontent.com/7038938/133766773-f0bd66f4-6206-4f76-93a2-1cd2fe861d24.png)
tried with and without `CLEARML__HOSTS__ELASTIC__EVENTS__ARGS__MAXSIZE: "100"` and `CLEARML__HOSTS__ELASTIC__WORKERS__ARGS__MAXSIZE: "4"` but no luck

**Comment by jkhenning** [comment]
Hi @exzhawk ,

Not sure what's the issue here, but you'll need to get the elasticsearch logs, not the apiserver logs (use `docker logs clearml-elastic`)
