### ISSUE TITLE
[Elasticsearch] Can't connect to ES with basic_auth

### ISSUE THREAD

**Issue by Mokto** [allegroai/clearml-server#97]
Hi,

I've tried so many things but i'm still unsuccessful using basic auth with Elasticsearch.

```
[2021-12-02 09:21:26,850] [9] [WARNING] [elasticsearch] GET http://es-internal-clearml.yyyy.xxxxx.com:9200/ [status:401 request:0.026s]
/opt/clearml/apiserver/elastic/initialize.py:86: ElasticsearchWarning: The client is unable to verify that the server is Elasticsearch due security privileges on the server side
  return not es.indices.get_template(name="events*")
[2021-12-02 09:21:26,852] [9] [WARNING] [elasticsearch] GET http://es-internal-clearml.yyyy.xxxxx.com:9200_template/events* [status:401 request:0.002s]
Traceback (most recent call last):
Loading config from /opt/clearml/apiserver/config/default
Loading config from file /opt/clearml/apiserver/config/default/apiserver.conf
Loading config from file /opt/clearml/apiserver/config/default/hosts.conf
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/clearml/apiserver/server.py", line 10, in <module>
    AppSequence(app).start(request_handlers=RequestHandlers())
  File "/opt/clearml/apiserver/server_init/app_sequence.py", line 40, in start
    self._init_dbs()
  File "/opt/clearml/apiserver/server_init/app_sequence.py", line 78, in _init_dbs
    empty_es = check_elastic_empty()
  File "/opt/clearml/apiserver/elastic/initialize.py", line 86, in check_elastic_empty
    return not es.indices.get_template(name="events*")
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 301, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 710, in get_template
    "GET", _make_path("_template", name), params=params, headers=headers
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 458, in perform_request
    raise e
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 426, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 287, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 338, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, 'security_exception', 'missing authentication credentials for REST request [/_template/events*]')
```

I always get this.
To make sure the credentials are passed correctly I logged them :
```
            http_auth = (
                cls.get_credentials(cluster_name)
                if cluster_config.get("secure", True)
                else None
            )

            args = cluster_config.get("args", {})
            log.warning(http_auth)
            _instances[cluster_name] = Elasticsearch(
                hosts=hosts, http_auth=http_auth, **args
            )
```
https://github.com/allegroai/clearml-server/blob/master/apiserver/es_factory.py#L84-L93
and it indeed returns a tuple with the proper username password.

Note: i'm settting those values through 4 env variables: CLEARML_ELASTIC_SERVICE_HOST, CLEARML_ELASTIC_SERVICE_PORT, CLEARML_ELASTIC_SERVICE_USERNAME, CLEARML_ELASTIC_SERVICE_PASSWORD

Has anyone ever managed to work with Es authentication?

What's weird is that I'm using Elasticsearch python in a different project, my constructor is really similar and it works.

**Comment by jkhenning** [comment]
Hi @Mokto ,

Thia seems like an issue with the initial script that updates the ES templates, not with the main server driver that handles read/write to ES. How are you deploying the server?

**Comment by Mokto** [comment]
Official helm (latest) chart.

Thanks.

**Comment by Mokto** [comment]
It's most probably coming from this line : https://github.com/allegroai/clearml-server/blob/master/apiserver/elastic/initialize.py#L85.

I'll try to fix it

**Comment by Mokto** [comment]
https://github.com/allegroai/clearml-server/pull/98

Should be fixed with this PR ;)

**Comment by jkhenning** [comment]
https://github.com/allegroai/clearml-server/pull/98 merged, thanks!
