### ISSUE TITLE
Use Podman To Run Docker-Compose - Permission Denied Error

### ISSUE THREAD

**Issue by Jason-Hsu** [allegroai/clearml-server#99]
Hi all,

I use RHEL 8.5 and use podman to run the docker-compose ([ref - Using Podman and Docker Compose](https://www.redhat.com/sysadmin/podman-docker-compose)), but encounter serveral permission denied error in serveral containers.

```
clearml-fileserver | Loading config from /opt/clearml/fileserver/config/default
clearml-fileserver | Loading config from file /opt/clearml/fileserver/config/default/fileserver.conf
clearml-fileserver | Loading config from file /opt/clearml/fileserver/config/default/logging.conf
clearml-fileserver | Loading config from /opt/clearml/config
clearml-fileserver | Traceback (most recent call last):
clearml-fileserver |   File "/usr/lib64/python3.6/logging/config.py", line 565, in configure
clearml-fileserver |     handler = self.configure_handler(handlers[name])
clearml-fileserver |   File "/usr/lib64/python3.6/logging/config.py", line 738, in configure_handler
clearml-fileserver |     result = factory(**kwargs)
clearml-fileserver |   File "/usr/lib64/python3.6/logging/handlers.py", line 150, in __init__
clearml-fileserver |     BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
clearml-fileserver |   File "/usr/lib64/python3.6/logging/handlers.py", line 57, in __init__
clearml-fileserver |     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
clearml-fileserver |   File "/usr/lib64/python3.6/logging/__init__.py", line 1032, in __init__
clearml-fileserver |     StreamHandler.__init__(self, self._open())
clearml-fileserver |   File "/usr/lib64/python3.6/logging/__init__.py", line 1061, in _open
clearml-fileserver |     return open(self.baseFilename, self.mode, encoding=self.encoding)
clearml-fileserver | PermissionError: [Errno 13] Permission denied: '/var/log/clearml/fileserver.log'
clearml-fileserver | 
clearml-fileserver | During handling of the above exception, another exception occurred:
clearml-fileserver | 
clearml-fileserver | Traceback (most recent call last):
clearml-fileserver |   File "fileserver.py", line 15, in <module>
clearml-fileserver |     from config import config
clearml-fileserver |   File "/opt/clearml/fileserver/config/__init__.py", line 8, in <module>
clearml-fileserver |     logging.config.dictConfig(config.get("logging"))
clearml-fileserver |   File "/usr/lib64/python3.6/logging/config.py", line 802, in dictConfig
clearml-fileserver |     dictConfigClass(config).configure()
clearml-fileserver |   File "/usr/lib64/python3.6/logging/config.py", line 573, in configure
clearml-fileserver |     '%r: %s' % (name, e))
clearml-fileserver | ValueError: Unable to configure handler 'text_file': [Errno 13] Permission denied: '/var/log/clearml/fileserver.log'
clearml-mongo    | chown: changing ownership of '/proc/1/fd/1': Permission denied
clearml-mongo    | chown: changing ownership of '/proc/1/fd/2': Permission denied
clearml-apiserver | Traceback (most recent call last):
clearml-apiserver |   File "/usr/lib64/python3.6/logging/config.py", line 565, in configure
clearml-apiserver |     handler = self.configure_handler(handlers[name])
clearml-apiserver |   File "/usr/lib64/python3.6/logging/config.py", line 738, in configure_handler
clearml-apiserver |     result = factory(**kwargs)
clearml-apiserver |   File "/usr/lib64/python3.6/logging/handlers.py", line 150, in __init__
clearml-apiserver |     BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
clearml-apiserver |   File "/usr/lib64/python3.6/logging/handlers.py", line 57, in __init__
clearml-apiserver |     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
clearml-apiserver |   File "/usr/lib64/python3.6/logging/__init__.py", line 1032, in __init__
clearml-apiserver |     StreamHandler.__init__(self, self._open())
clearml-apiserver |   File "/usr/lib64/python3.6/logging/__init__.py", line 1061, in _open
clearml-apiserver |     return open(self.baseFilename, self.mode, encoding=self.encoding)
clearml-apiserver | PermissionError: [Errno 13] Permission denied: '/var/log/clearml/apiserver.log'
clearml-apiserver | 
clearml-apiserver | During handling of the above exception, another exception occurred:
clearml-apiserver | 
clearml-apiserver | Traceback (most recent call last):
clearml-apiserver |   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
clearml-apiserver |     "__main__", mod_spec)
clearml-apiserver |   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
clearml-apiserver |     exec(code, run_globals)
clearml-apiserver |   File "/opt/clearml/apiserver/server.py", line 5, in <module>
clearml-apiserver |     from apiserver.config_repo import config
clearml-apiserver |   File "/opt/clearml/apiserver/config_repo.py", line 4, in <module>
clearml-apiserver |     config.initialize_logging()
clearml-apiserver |   File "/opt/clearml/apiserver/config/basic.py", line 206, in initialize_logging
clearml-apiserver |     logging.config.dictConfig(logging_config)
clearml-apiserver |   File "/usr/lib64/python3.6/logging/config.py", line 802, in dictConfig
clearml-apiserver |     dictConfigClass(config).configure()
clearml-apiserver |   File "/usr/lib64/python3.6/logging/config.py", line 573, in configure
clearml-apiserver |     '%r: %s' % (name, e))
clearml-apiserver | ValueError: Unable to configure handler 'text_file': [Errno 13] Permission denied: '/var/log/clearml/apiserver.log'

```

Thanks

**Comment by jkhenning** [comment]
Hi @Jason-Hsu ,

Are you sure the containers are run in privileged mode? They should be.

**Comment by Jason-Hsu** [comment]
Hi @jkhenning ,

No, I think they aren't run in privileged mode. I'm not sure, but I'm thinking podman has more restriction on it.

**Comment by jkhenning** [comment]
If not, you will have to change some of the default configurations. What I see here from the logs is that we can't have the services log to `/var/log/clearml` since that requires root access

**Comment by Jason-Hsu** [comment]
I spent some time surveying podman related info, but I can't still make it work.
- [Using volumes with rootless podman, explained](https://www.tutorialworks.com/podman-rootless-volumes/)

Finally, I determine not to use podman, but change to use Docker and now it can work.

**Comment by jkhenning** [comment]
Hi @Jason-Hsu ,

OK. If you happen to come across any relevant info on the matter, I'll be happy to hear about it
